// supabase/functions/send-report/index.ts
// Called by a Supabase cron job every Monday 08:00 Cairo time
// Sends weekly HTML summary email via Resend to all admins + coordinators

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY")!;
const FROM_EMAIL     = "reports@suezstraytracker.org";

const supabase = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
);

serve(async () => {
  // Fetch zone stats
  const { data: zones } = await supabase
    .from("zone_stats")
    .select("*")
    .order("total_dogs", { ascending: false });

  // Fetch dogs added this week
  const weekAgo = new Date(Date.now() - 7 * 864e5).toISOString();
  const { count: newDogs } = await supabase
    .from("dogs")
    .select("*", { count: "exact", head: true })
    .gte("created_at", weekAgo);

  const { count: newTnr } = await supabase
    .from("dogs")
    .select("*", { count: "exact", head: true })
    .eq("tnr_done", true)
    .gte("tnr_date", weekAgo.substring(0, 10));

  const { count: urgentSightings } = await supabase
    .from("sightings")
    .select("*", { count: "exact", head: true })
    .in("urgency", ["high", "critical"])
    .gte("created_at", weekAgo);

  const totalDogs  = zones?.reduce((a, z) => a + Number(z.total_dogs), 0) ?? 0;
  const totalTnr   = zones?.reduce((a, z) => a + Number(z.tnr_count), 0) ?? 0;
  const tnrPct     = totalDogs ? Math.round(totalTnr / totalDogs * 100) : 0;

  const zoneRows = zones?.map(z =>
    `<tr>
      <td>${z.name_en}</td>
      <td style="text-align:center">${z.total_dogs}</td>
      <td style="text-align:center">${z.tnr_count}</td>
      <td style="text-align:center">${z.vaccinated_count}</td>
      <td style="text-align:center">${z.total_dogs ? Math.round(Number(z.tnr_count)/Number(z.total_dogs)*100) : 0}%</td>
    </tr>`
  ).join("") ?? "";

  const html = `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Weekly Report</title>
<style>
  body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
  h1 { color: #c8860a; }
  .stats { display: flex; gap: 16px; margin: 20px 0; }
  .stat { background: #f5f0e8; border-radius: 8px; padding: 16px; flex: 1; text-align: center; }
  .stat-num { font-size: 32px; font-weight: bold; color: #c8860a; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th { background: #c8860a; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #eee; }
  tr:nth-child(even) td { background: #f9f9f9; }
  .footer { margin-top: 32px; font-size: 12px; color: #999; }
</style>
</head>
<body>
  <h1>🐕 Suez Stray Tracker — Weekly Report</h1>
  <p>Week ending ${new Date().toLocaleDateString("en-GB", { timeZone: "Africa/Cairo" })}</p>
  
  <div style="background:#fff8ee;border-left:4px solid #c8860a;padding:12px 16px;margin:16px 0;border-radius:0 8px 8px 0;">
    <strong>This week:</strong> ${newDogs} new dogs logged · ${newTnr} TNR operations · ${urgentSightings} urgent sightings
  </div>

  <div class="stats">
    <div class="stat"><div class="stat-num">${totalDogs}</div>Total tracked</div>
    <div class="stat"><div class="stat-num">${totalTnr}</div>TNR'd</div>
    <div class="stat"><div class="stat-num">${tnrPct}%</div>TNR rate</div>
  </div>

  <h2>Zone breakdown</h2>
  <table>
    <thead>
      <tr><th>Zone</th><th>Total</th><th>TNR</th><th>Vaccinated</th><th>TNR %</th></tr>
    </thead>
    <tbody>${zoneRows}</tbody>
  </table>

  <div class="footer">
    This report is automatically generated by Suez Stray Tracker.
    Log in to view full details and export data.
  </div>
</body>
</html>`;

  // Get admin + coordinator emails
  const { data: admins } = await supabase
    .from("profiles")
    .select("id")
    .in("role", ["admin", "coordinator"]);

  if (!admins?.length) {
    return new Response("No admins", { status: 200 });
  }

  const adminIds = admins.map(a => a.id);
  const { data: users } = await supabase.auth.admin.listUsers();
  const adminEmails = users?.users
    .filter(u => adminIds.includes(u.id))
    .map(u => u.email)
    .filter(Boolean) ?? [];

  // Send via Resend
  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to: adminEmails,
      subject: `🐕 Weekly Report — ${totalDogs} dogs tracked, ${tnrPct}% TNR'd`,
      html,
    }),
  });

  return new Response(JSON.stringify({ ok: true, sent_to: adminEmails.length }), {
    headers: { "Content-Type": "application/json" },
  });
});
